// Stage 9 — grammatically-correct bracket resolution (deterministic text
// bridging, NOT an LLM call). When a UFGS selection resolves, deleting the
// unchosen bracketed options must not leave stray punctuation/conjunctions, and
// the retained items must read as a clean list. Two entry points:
//
//   • bridgeBrackets(source, isChosen) — the full raw-source bridge: parses the
//     `[...]` spans of an original UFGS sentence, keeps chosen CONTENT items,
//     deletes unchosen ones AND the editorial conjunction/punctuation brackets
//     ([and], [,]), then regenerates the connecting conjunction before the final
//     retained item and normalizes the seams. This is the worked-example contract.
//
//   • repairSeams(text) — the normalizer alone, applied at the emit seam
//     (resolveParagraphText) after selection placeholders are substituted, so an
//     omitted selection (empty substitution) can never leave a doubled comma,
//     a leading/trailing stray comma, or collapsed double spaces in issued text.
//
// Both are pure and deterministic (no model, no I/O).

// Conjunctions the UFGS master brackets as editorial glue. We DROP the bracketed
// form and REGENERATE the conjunction in the grammatically-correct position.
const CONJUNCTIONS = new Set(['and', 'or', 'and/or', 'nor']);
const PUNCT_ONLY = /^[\s.,;:/&()-]*$/;

type BracketClass = 'conjunction' | 'punct' | 'content';

function classify(inner: string): BracketClass {
  const t = inner.trim();
  if (PUNCT_ONLY.test(t)) return 'punct';
  if (CONJUNCTIONS.has(t.toLowerCase())) return 'conjunction';
  return 'content';
}

// Strip wrapping commas/semicolons/whitespace from a chosen item's inner text so
// `,existing uncoated surfaces,` -> `existing uncoated surfaces` (the list
// separators are regenerated by the bridge, not carried verbatim).
function cleanItem(inner: string): string {
  return inner.replace(/^[\s,;]+/, '').replace(/[\s,;]+$/, '').trim();
}

// Force an Oxford-style list with "and" before the FINAL item, even for a single
// item (which reads as a continuation of the preceding phrase — see the worked
// example: "new surfaces, and existing uncoated surfaces").
function joinWithAnd(items: string[], conj = 'and'): string {
  if (items.length === 0) return '';
  if (items.length === 1) return `${conj} ${items[0]}`;
  return `${items.slice(0, -1).join(', ')}, ${conj} ${items[items.length - 1]}`;
}

interface Node {
  type: 'text' | 'bracket';
  value: string; // text run, or the bracket INNER (without the [ ])
  klass?: BracketClass;
}

// Depth-aware top-level parse: a nested span like `[, including [_____]]` is a
// SINGLE top-level bracket node (its inner keeps the nested markup verbatim).
function parse(source: string): Node[] {
  const nodes: Node[] = [];
  let buf = '';
  for (let i = 0; i < source.length; ) {
    if (source[i] !== '[') {
      buf += source[i++];
      continue;
    }
    let depth = 0;
    let j = i;
    for (; j < source.length; j++) {
      if (source[j] === '[') depth++;
      else if (source[j] === ']' && --depth === 0) break;
    }
    if (j >= source.length) {
      // Unmatched '[' — leave literal (a downstream hygiene scan surfaces it).
      buf += source[i++];
      continue;
    }
    if (buf) {
      nodes.push({ type: 'text', value: buf });
      buf = '';
    }
    const inner = source.slice(i + 1, j);
    nodes.push({ type: 'bracket', value: inner, klass: classify(inner) });
    i = j + 1;
  }
  if (buf) nodes.push({ type: 'text', value: buf });
  return nodes;
}

const isWhitespace = (s: string) => /^\s*$/.test(s);

// Render one bracket GROUP (a run of bracket nodes separated only by whitespace)
// given which of its CONTENT brackets were chosen.
function renderGroup(group: Node[], chosenFlags: boolean[]): string {
  const contentInners: { inner: string; chosen: boolean }[] = [];
  let hasConjunction = false;
  let hasLeadingComma = false;
  let ci = 0;
  for (const n of group) {
    if (n.type !== 'bracket') continue;
    if (n.klass === 'conjunction') hasConjunction = true;
    else if (n.klass === 'content') {
      const chosen = chosenFlags[ci++] ?? false;
      if (n.value.trim().startsWith(',') || n.value.trim().startsWith(';')) hasLeadingComma = true;
      contentInners.push({ inner: n.value, chosen });
    }
  }
  const items = contentInners.filter((c) => c.chosen).map((c) => cleanItem(c.inner)).filter(Boolean);
  if (items.length === 0) return '';

  // List mode: the group reads as a list continuation (it carried a bracketed
  // conjunction, a leading comma, or more than one content option). Render with
  // a leading separator + regenerated "and" before the final item.
  const listMode = hasConjunction || hasLeadingComma || contentInners.length > 1;
  if (listMode) return `, ${joinWithAnd(items)}`;
  // Inline include: a lone optional span, no list punctuation — just its text.
  return items.join(', ');
}

// The full raw-source bridge. `isChosen(contentIndex)` decides each CONTENT
// bracket (0-based across the whole source, in order); conjunction/punctuation
// brackets ignore the predicate (always regenerated/dropped).
export function bridgeBrackets(source: string, isChosen: (contentIndex: number) => boolean): string {
  const nodes = parse(source);
  let out = '';
  let contentIndex = 0;
  for (let i = 0; i < nodes.length; ) {
    const n = nodes[i];
    if (n.type === 'text') {
      out += n.value;
      i++;
      continue;
    }
    // Collect the maximal group: consecutive bracket nodes, absorbing
    // whitespace-only text nodes that sit between them.
    const group: Node[] = [];
    let j = i;
    while (j < nodes.length) {
      if (nodes[j].type === 'bracket') {
        group.push(nodes[j]);
        j++;
      } else if (nodes[j].type === 'text' && isWhitespace(nodes[j].value) && j + 1 < nodes.length && nodes[j + 1].type === 'bracket') {
        j++; // skip inter-bracket whitespace, stays inside the group
      } else break;
    }
    const flags: boolean[] = [];
    for (const g of group) if (g.type === 'bracket' && g.klass === 'content') flags.push(isChosen(contentIndex++));
    out += renderGroup(group, flags);
    i = j;
  }
  // A list group at the very START of the sentence renders a leading ", and X" —
  // strip the dangling separator/conjunction (only meaningful at string start,
  // so it is done here, not in the general-purpose repairSeams).
  out = out.replace(/^\s*,\s*(?:and|or|and\/or|nor)\b\s*/i, '').replace(/^\s*,\s*/, '');
  return repairSeams(out);
}

// Seam normalizer — conservative and idempotent. Fixes exactly the artifacts a
// bracket deletion/substitution leaves: doubled/stray commas, space-before-
// punctuation, and collapsed double spaces. Does NOT touch newlines or single
// spaces, so clean text passes through unchanged.
export function repairSeams(text: string): string {
  let t = text;
  // Collapse runs of spaces/tabs (an omitted selection leaves a gap).
  t = t.replace(/[ \t]{2,}/g, ' ');
  // Remove whitespace directly before a comma/period/semicolon/colon/close-paren.
  t = t.replace(/[ \t]+([,.;:)])/g, '$1');
  // Collapse doubled commas/semicolons ( ",," / ", ," ) into one.
  t = t.replace(/([,;])(?:[ \t]*[,;])+/g, '$1');
  // Ensure a single space after a comma/semicolon that is followed by a letter
  // or digit (a deletion can butt a comma against the next word).
  t = t.replace(/([,;])(?=[A-Za-z0-9])/g, '$1 ');
  // Drop a trailing stray separator before end/period.
  t = t.replace(/[ \t]*[,;](?=[ \t]*$)/, '');
  // Final space cleanup.
  t = t.replace(/[ \t]{2,}/g, ' ');
  return t.trim();
}
