// CHANGE-04 Part 6 — UFGS master ETL. Reads the real WBDG UFGS section files
// (documents/UFGS_M/*.SEC) and emits a D1 seed of the REAL controlled lists:
//   • UMRL  — the union of every REFERENCES article (the master reference list).
//   • UMSL  — every SUBMITTALS article, keyed by section.
//   • corpus_source — provenance for UMRL/UMSL + the on-hand UFC documents (G12).
//
// Run:  node scripts/etl-ufgs.ts  (Node 24 strips types natively)
// Output: db/generated/seed-umrl-umsl.sql  (gitignored — bulk regenerable data)
//
// This REPLACES the illustrative Mode A seeds (db/seed.sql's UMRL rows). The UFC
// PDFs are CID-font encoded and not cleanly text-extractable in-repo, so UFC
// CLAUSES are NOT invented (G7): only the documents' provenance/edition is
// recorded, pending a proper text layer. That is the honest state per Part 0.2.

import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { parseSecReferences, parseSecSubmittals } from '../src/corpus/sec-parser.ts';

const DIR = 'documents/UFGS_M';
const OUT = 'db/generated/seed-umrl-umsl.sql';
const MASTER_EDITION = 'UFGS Master (.SEC, 2021-2025)';

const q = (s: string) => `'${(s ?? '').replace(/'/g, "''")}'`;
const sectionFromName = (name: string): string | null => {
  const m = name.match(/^(\d{2} \d{2} \d{2})/);
  return m ? m[1] : null;
};

function main() {
  const files = readdirSync(DIR).filter((f) => f.toUpperCase().endsWith('.SEC'));
  const refByKey = new Map<string, { org: string; designation: string; editionDate: string; title: string }>();
  const subRows: { section: string; sdCode: string; item: string; classification: string }[] = [];

  for (const f of files) {
    let xml: string;
    try { xml = readFileSync(`${DIR}/${f}`, 'latin1'); } catch { continue; }
    for (const r of parseSecReferences(xml)) {
      if (!r.designation || !r.org) continue;
      const key = `${r.org}|${r.designation}`;
      if (!refByKey.has(key)) refByKey.set(key, r); // dedup: keep first-seen edition
    }
    const section = sectionFromName(f);
    if (!section) continue;
    for (const s of parseSecSubmittals(xml)) {
      if (!s.item) continue;
      subRows.push({ section, sdCode: s.sdCode, item: s.item, classification: s.classification });
    }
  }

  const lines: string[] = [];
  lines.push('-- GENERATED by scripts/etl-ufgs.ts from the real UFGS .SEC master — do not edit.');
  lines.push('-- Real UMRL/UMSL replacing the illustrative Mode A seeds (G12). Regenerate: node scripts/etl-ufgs.ts');
  lines.push('');
  lines.push("-- Remove the pre-CHANGE-04 illustrative Mode A rows (G12).");
  lines.push("DELETE FROM ref_list WHERE list_id = 'UMRL';");
  lines.push("DELETE FROM sub_list WHERE list_id = 'UMRL';");
  lines.push("DELETE FROM criteria WHERE profile = 'ufc';");
  lines.push("DELETE FROM corpus_source WHERE kind IN ('UMRL','UMSL','UFC');");
  lines.push('');

  // Provenance (G12) — write BEFORE the rows that reference the edition.
  lines.push('INSERT INTO corpus_source (source_id, kind, identifier, edition, ingested_at, stale) VALUES');
  lines.push(`  ('cs-umrl', 'UMRL', 'UMRL', ${q(MASTER_EDITION)}, datetime('now'), 0),`);
  lines.push(`  ('cs-umsl', 'UMSL', 'UMSL', ${q(MASTER_EDITION)}, datetime('now'), 0),`);
  lines.push(`  ('cs-ufc-1-300-02', 'UFC', 'UFC 1-300-02', '2025', datetime('now'), 0),`);
  lines.push(`  ('cs-ufc-4-510-01', 'UFC', 'UFC 4-510-01', 'w/ Change 4 (2023)', datetime('now'), 0);`);
  lines.push('-- NOTE: UFC clause TEXT is not loaded — the supplied UFC PDFs are CID-font');
  lines.push('-- encoded and not cleanly text-extractable in-repo. Editions are captured');
  lines.push('-- above (G7); clauses await a real text layer / manual entry (Part 0.2).');
  lines.push('');

  // UMRL — one INSERT per batch of 200 rows.
  const refs = [...refByKey.values()];
  emitBatched(lines, 'ref_list (rid, list_id, org, designation, edition_date, title, active, source_edition, verified_at, stale)', refs.map((r, i) =>
    `(${q('rid-u-' + i)}, 'UMRL', ${q(r.org)}, ${q(r.designation)}, ${q(r.editionDate || 'n/a')}, ${q(r.title)}, 1, ${q(MASTER_EDITION)}, datetime('now'), 0)`,
  ));

  // UMSL — list_id 'UMRL' is the Mode A validator authority (ctx.referenceListId);
  // provenance is tracked via corpus_source kind 'UMSL'.
  emitBatched(lines, 'sub_list (usid, list_id, section, sd_code, item, default_class, notes, source_edition, verified_at, stale)', subRows.map((s, i) =>
    `(${q('usid-u-' + i)}, 'UMRL', ${q(s.section)}, ${q(s.sdCode)}, ${q(s.item)}, ${q(s.classification)}, ${q('UFGS ' + s.section)}, ${q(MASTER_EDITION)}, datetime('now'), 0)`,
  ));

  mkdirSync('db/generated', { recursive: true });
  writeFileSync(OUT, lines.join('\n') + '\n');
  console.log(`Wrote ${OUT}`);
  console.log(`  UMRL references (distinct): ${refs.length}`);
  console.log(`  UMSL submittals: ${subRows.length}`);
}

function emitBatched(lines: string[], into: string, values: string[]) {
  const B = 200;
  for (let i = 0; i < values.length; i += B) {
    const batch = values.slice(i, i + B);
    lines.push(`INSERT INTO ${into} VALUES`);
    lines.push(batch.join(',\n') + ';');
    lines.push('');
  }
}

main();
