// CHANGE-05 §4 — seed the SEC CATALOG (section + title) into `ufgs_corpus_section`
// so the lexical section matcher (src/manual/sec-match.ts) can run end-to-end in
// the app WITHOUT the full R2 IR ingestion. Selection needs only section + title;
// drafting still needs the R2 corpus (npm run etl:ufgs-corpus), which also writes
// these rows — this is the fast, catalog-only path for the selection demo.
//
// Dependency-light (mirrors scripts/etl-ufgs.ts): own file reading + regex, no
// src/ imports, so `node scripts/etl-sec-catalog.ts` runs clean. Emits
// db/generated/seed-sec-catalog.sql (gitignored). Load with:
//   npm run db:seed:sec-catalog

import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';

const DIR = 'documents/UFGS_M';
const OUT = 'db/generated/seed-sec-catalog.sql';

const esc = (s: string) => s.replace(/'/g, "''");

function extract(xml: string, fallbackSection: string): { section: string; title: string; edition: string } {
  const hdr = xml.match(/UFGS-([0-9][0-9 ]+?[0-9])\s*\(([^)]+)\)/);
  const section = hdr ? hdr[1].replace(/\s+/g, ' ').trim() : fallbackSection;
  const edition = hdr ? hdr[2].trim() : 'catalog-dev';
  const stl = xml.match(/<STL>([\s\S]*?)<\/STL>/);
  const title = stl ? stl[1].replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim() : section;
  return { section, title, edition };
}

function main(): void {
  const files = readdirSync(DIR).filter((f) => f.toUpperCase().endsWith('.SEC'));
  const now = new Date().toISOString();
  const seen = new Set<string>();
  const rows: string[] = [];
  for (const f of files) {
    const xml = readFileSync(`${DIR}/${f}`, 'latin1');
    const { section, title, edition } = extract(xml, f.replace(/\.SEC$/i, ''));
    if (seen.has(section)) continue;
    seen.add(section);
    // Canonical section->key: collapse EVERY non-alphanumeric run to a dash so an
    // extended number like "01 31 23.13 20" -> "01-31-23-13-20" matches the object
    // the ingest actually wrote (previously only spaces were replaced, so the dot
    // survived and the key pointed at a non-existent object). Keep this in lockstep
    // with ufgsCorpusR2Key() in src/corpus/ufgs-store.ts.
    const r2Key = `corpus/ufgs/${section.replace(/[^0-9A-Za-z]+/g, '-')}.json`;
    rows.push(
      `INSERT OR REPLACE INTO ufgs_corpus_section (section, title, r2_key, vectorize_ns, source_edition, ingested_at) ` +
        `VALUES ('${esc(section)}', '${esc(title)}', '${esc(r2Key)}', 'ufgs', '${esc(edition)}', '${now}');`,
    );
  }
  // CHANGE-07 §7 — prune sections that fell out of the corpus. INSERT OR REPLACE
  // never deletes, so a shrunk master would otherwise leave stale catalog rows the
  // outline matcher could still propose. This DELETE + the INSERTs apply atomically
  // in one `wrangler d1 execute --file` run.
  const keep = [...seen].map((s) => `'${esc(s)}'`).join(', ');
  const prune = keep
    ? `DELETE FROM ufgs_corpus_section WHERE section NOT IN (${keep});`
    : `DELETE FROM ufgs_corpus_section;`;

  mkdirSync('db/generated', { recursive: true });
  // No explicit BEGIN TRANSACTION/COMMIT: `wrangler d1 execute --remote --file`
  // rejects those ("use state.storage.transaction()"), and D1 already wraps a
  // --file run atomically. The INSERT OR REPLACE rows are idempotent on their own,
  // so the file applies cleanly both --local and --remote (deploy reseeds it).
  writeFileSync(OUT, `-- generated by scripts/etl-sec-catalog.ts — ${rows.length} sections\n${prune}\n${rows.join('\n')}\n`);
  console.log(`Wrote ${rows.length} catalog rows to ${OUT}`);
}

main();
